<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Operations;

use \kohortpay\sdk\Utils\SpeakeasyMetadata;
class CancelPaymentIntentSecurity
{
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $bearer = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $bearer1 = null;
    
	public function __construct()
	{
		$this->bearer = null;
		$this->bearer1 = null;
	}
}
