<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Operations;

use \kohortpay\sdk\Utils\SpeakeasyMetadata;
class PaymentIntentsControllerFindOneRequest
{
    /**
     * ID of the Payment Intent to fetch
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->id = "";
	}
}
