<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Operations;

use \kohortpay\sdk\Utils\SpeakeasyMetadata;
class UpdateRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \kohortpay\sdk\Models\Components\UpdatePaymentGroupDto $updatePaymentGroupDto;
    
	public function __construct()
	{
		$this->id = "";
		$this->updatePaymentGroupDto = new \kohortpay\sdk\Models\Components\UpdatePaymentGroupDto();
	}
}
