<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class BadRequestResponse
{
    /**
     * Details of the error.
     * 
     * @var \kohortpay\sdk\Models\Components\ErrorDetail $error
     */
	#[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\ErrorDetail')]
    public ErrorDetail $error;
    
	public function __construct()
	{
		$this->error = new \kohortpay\sdk\Models\Components\ErrorDetail();
	}
}
