<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class CreateAddressDto
{
    /**
     * The first line of the address.
     * 
     * @var string $addressLine1
     */
	#[\JMS\Serializer\Annotation\SerializedName('addressLine1')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $addressLine1;
    
    /**
     * The second line of the address (optional).
     * 
     * @var ?string $addressLine2
     */
	#[\JMS\Serializer\Annotation\SerializedName('addressLine2')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $addressLine2 = null;
    
    /**
     * The city of the address.
     * 
     * @var string $city
     */
	#[\JMS\Serializer\Annotation\SerializedName('city')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $city;
    
    /**
     * The postal code of the address.
     * 
     * @var string $postalCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('postalCode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $postalCode;
    
    /**
     * The country of the address.
     * 
     * @var string $country
     */
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $country;
    
    /**
     * The state of the address (optional).
     * 
     * @var ?string $state
     */
	#[\JMS\Serializer\Annotation\SerializedName('state')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $state = null;
    
	public function __construct()
	{
		$this->addressLine1 = "";
		$this->addressLine2 = null;
		$this->city = "";
		$this->postalCode = "";
		$this->country = "";
		$this->state = null;
	}
}
