<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


/**
 * CreatePaymentGroupDtoMetadata - Additional metadata for the payment group.
 * 
 * @package kohortpay\sdk\Models\Components
 * @access public
 */
class CreatePaymentGroupDtoMetadata
{
	public function __construct()
	{
	}
}
