<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class CreatePaymentIntentDto
{
    /**
     * The amount to be charged.
     * 
     * @var float $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $amount;
    
    /**
     * Checkout Session id of the payment intent
     * 
     * @var string $checkoutSessionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('checkoutSessionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $checkoutSessionId;
    
    /**
     * Customer id of the payment intent
     * 
     * @var ?string $customerId
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerId = null;
    
    /**
     * Additional metadata for the payment group.
     * 
     * @var ?\kohortpay\sdk\Models\Components\Metadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\Metadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Metadata $metadata = null;
    
    /**
     * Status of the payment intent
     * 
     * @var ?\kohortpay\sdk\Models\Components\Status $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<kohortpay\sdk\Models\Components\Status>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Status $status = null;
    
	public function __construct()
	{
		$this->amount = 0;
		$this->checkoutSessionId = "";
		$this->customerId = null;
		$this->metadata = null;
		$this->status = null;
	}
}
