<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class CreatePaymentGroupDto
{
    /**
     * The ID of the customer.
     * 
     * @var string $customerId
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $customerId;
    
    /**
     * The ID of the payment intent.
     * 
     * @var string $paymentIntentId
     */
	#[\JMS\Serializer\Annotation\SerializedName('paymentIntentId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $paymentIntentId;
    
    /**
     * Additional metadata for the payment group.
     * 
     * @var ?\kohortpay\sdk\Models\Components\CreatePaymentGroupDtoMetadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\CreatePaymentGroupDtoMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreatePaymentGroupDtoMetadata $metadata = null;
    
    /**
     * The expiration date and time of the payment group.
     * 
     * @var ?\DateTime $expiresAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiresAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiresAt = null;
    
	public function __construct()
	{
		$this->customerId = "";
		$this->paymentIntentId = "";
		$this->metadata = null;
		$this->expiresAt = null;
	}
}
