<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


/**
 * CreateCustomerDtoMetadata - Additional metadata for the  customer.
 * 
 * @package kohortpay\sdk\Models\Components
 * @access public
 */
class CreateCustomerDtoMetadata
{
	public function __construct()
	{
	}
}
