<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class CreateCustomerDto
{
    /**
     * The primary email address of the user.
     * 
     * @var string $emailAddress
     */
	#[\JMS\Serializer\Annotation\SerializedName('emailAddress')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $emailAddress;
    
    /**
     * The first name of the customer.
     * 
     * @var ?string $firstName
     */
	#[\JMS\Serializer\Annotation\SerializedName('firstName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $firstName = null;
    
    /**
     * The last name of the customer.
     * 
     * @var ?string $lastName
     */
	#[\JMS\Serializer\Annotation\SerializedName('lastName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $lastName = null;
    
    /**
     * The phone number of the customer.
     * 
     * @var ?string $phoneNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('phoneNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $phoneNumber = null;
    
    /**
     * The address of the customer.
     * 
     * @var ?\kohortpay\sdk\Models\Components\CreateAddressDto $address
     */
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\CreateAddressDto')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateAddressDto $address = null;
    
    /**
     * The shipping address of the customer.
     * 
     * @var ?\kohortpay\sdk\Models\Components\CreateAddressDto $shippingAddress
     */
	#[\JMS\Serializer\Annotation\SerializedName('shippingAddress')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\CreateAddressDto')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateAddressDto $shippingAddress = null;
    
    /**
     * Additional metadata for the  customer.
     * 
     * @var ?\kohortpay\sdk\Models\Components\CreateCustomerDtoMetadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\CreateCustomerDtoMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateCustomerDtoMetadata $metadata = null;
    
	public function __construct()
	{
		$this->emailAddress = "";
		$this->firstName = null;
		$this->lastName = null;
		$this->phoneNumber = null;
		$this->address = null;
		$this->shippingAddress = null;
		$this->metadata = null;
	}
}
