<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


class CreateCheckoutSessionDto
{
    /**
     * The URL to redirect the user to upon successful payment.
     * 
     * @var ?string $successUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('successUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $successUrl = null;
    
    /**
     * The URL to redirect the user to upon cancellation of payment.
     * 
     * @var ?string $cancelUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancelUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cancelUrl = null;
    
    /**
     * The email of the customer.
     * 
     * @var ?string $customerEmail
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerEmail')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerEmail = null;
    
    /**
     * The firstName of the customer.
     * 
     * @var ?string $customerFirstName
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerFirstName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerFirstName = null;
    
    /**
     * The lastName of the customer.
     * 
     * @var ?string $customerLastName
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerLastName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerLastName = null;
    
    /**
     * The unique id of the customer
     * 
     * @var ?string $customerId
     */
	#[\JMS\Serializer\Annotation\SerializedName('customerId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerId = null;
    
    /**
     * The expiration date of the checkout session.
     * 
     * @var ?\DateTime $expiresAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiresAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiresAt = null;
    
    /**
     * List of items in the checkout session.
     * 
     * @var array<\kohortpay\sdk\Models\Components\CreateLineItemDto> $lineItems
     */
	#[\JMS\Serializer\Annotation\SerializedName('lineItems')]
    #[\JMS\Serializer\Annotation\Type('array<kohortpay\sdk\Models\Components\CreateLineItemDto>')]
    public array $lineItems;
    
    /**
     * Additional metadata for the checkout session.
     * 
     * @var ?\kohortpay\sdk\Models\Components\CreateCheckoutSessionDtoMetadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('kohortpay\sdk\Models\Components\CreateCheckoutSessionDtoMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateCheckoutSessionDtoMetadata $metadata = null;
    
    /**
     * The total amount of the checkout session
     * 
     * @var float $amountTotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('amountTotal')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $amountTotal;
    
    /**
     * The locale of the checkout session. default: fr_FR
     * 
     * @var string $locale
     */
	#[\JMS\Serializer\Annotation\SerializedName('locale')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $locale;
    
	public function __construct()
	{
		$this->successUrl = null;
		$this->cancelUrl = null;
		$this->customerEmail = null;
		$this->customerFirstName = null;
		$this->customerLastName = null;
		$this->customerId = null;
		$this->expiresAt = null;
		$this->lineItems = [];
		$this->metadata = null;
		$this->amountTotal = 0;
		$this->locale = "";
	}
}
