<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk\Models\Components;


/** Status of the payment intent */
enum Status: string
{
    case Canceled = 'CANCELED';
    case Processing = 'PROCESSING';
    case RequiresPaymentMethod = 'REQUIRES_PAYMENT_METHOD';
    case RequiresConfirmation = 'REQUIRES_CONFIRMATION';
    case RequiresAction = 'REQUIRES_ACTION';
    case RequiresCapture = 'REQUIRES_CAPTURE';
    case Succeeded = 'SUCCEEDED';
}
