<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk;

class Customers 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * find All customers of an organization.
     * 
     * @return \kohortpay\sdk\Models\Operations\CustomersControllerFindAllResponse
     */
	public function customersControllerFindAll(
    ): \kohortpay\sdk\Models\Operations\CustomersControllerFindAllResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/customers');
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CustomersControllerFindAllResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * Create a new customer.
     * 
     * Create a new customer.
     * 
     * @param \kohortpay\sdk\Models\Components\CreateCustomerDto $request
     * @return \kohortpay\sdk\Models\Operations\CustomersControllerCreateResponse
     */
	public function customersControllerCreate(
        \kohortpay\sdk\Models\Components\CreateCustomerDto $request,
    ): \kohortpay\sdk\Models\Operations\CustomersControllerCreateResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/customers');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CustomersControllerCreateResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * customersControllerRemove
     * 
     * @param string $id
     * @return \kohortpay\sdk\Models\Operations\CustomersControllerRemoveResponse
     */
	public function customersControllerRemove(
        string $id,
    ): \kohortpay\sdk\Models\Operations\CustomersControllerRemoveResponse
    {
        $request = new \kohortpay\sdk\Models\Operations\CustomersControllerRemoveRequest();
        $request->id = $id;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/customers/{id}', \kohortpay\sdk\Models\Operations\CustomersControllerRemoveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CustomersControllerRemoveResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * find All customers of an organization.
     * 
     * @param string $id
     * @return \kohortpay\sdk\Models\Operations\CustomersControllerFindOneResponse
     */
	public function customersControllerFindOne(
        string $id,
    ): \kohortpay\sdk\Models\Operations\CustomersControllerFindOneResponse
    {
        $request = new \kohortpay\sdk\Models\Operations\CustomersControllerFindOneRequest();
        $request->id = $id;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/customers/{id}', \kohortpay\sdk\Models\Operations\CustomersControllerFindOneRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CustomersControllerFindOneResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * customersControllerUpdate
     * 
     * @param string $id
     * @param \kohortpay\sdk\Models\Components\UpdateCustomerDto $updateCustomerDto
     * @return \kohortpay\sdk\Models\Operations\CustomersControllerUpdateResponse
     */
	public function customersControllerUpdate(
        string $id,
        \kohortpay\sdk\Models\Components\UpdateCustomerDto $updateCustomerDto,
    ): \kohortpay\sdk\Models\Operations\CustomersControllerUpdateResponse
    {
        $request = new \kohortpay\sdk\Models\Operations\CustomersControllerUpdateRequest();
        $request->id = $id;
        $request->updateCustomerDto = $updateCustomerDto;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/customers/{id}', \kohortpay\sdk\Models\Operations\CustomersControllerUpdateRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "updateCustomerDto", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('PATCH', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CustomersControllerUpdateResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
}