<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace kohortpay\sdk;

class PaymentIntents 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Retrieve all Payment Intents
     * 
     * @return \kohortpay\sdk\Models\Operations\FindAllPaymentIntentsResponse
     */
	public function findAll(
    ): \kohortpay\sdk\Models\Operations\FindAllPaymentIntentsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/payment-intents');
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\FindAllPaymentIntentsResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
	
    /**
     * Create a new Payment Intent
     * 
     * @param \kohortpay\sdk\Models\Components\CreatePaymentIntentDto $request
     * @return \kohortpay\sdk\Models\Operations\CreatePaymentIntentResponse
     */
	public function create(
        \kohortpay\sdk\Models\Components\CreatePaymentIntentDto $request,
    ): \kohortpay\sdk\Models\Operations\CreatePaymentIntentResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/payment-intents');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CreatePaymentIntentResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 201) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->createPaymentIntentDto = $serializer->deserialize((string)$httpResponse->getBody(), 'kohortpay\sdk\Models\Components\CreatePaymentIntentDto', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * Retrieve a Payment Intent by ID
     * 
     * @param string $id
     * @return \kohortpay\sdk\Models\Operations\FindOnePaymentIntentResponse
     */
	public function findOne(
        string $id,
    ): \kohortpay\sdk\Models\Operations\FindOnePaymentIntentResponse
    {
        $request = new \kohortpay\sdk\Models\Operations\FindOnePaymentIntentRequest();
        $request->id = $id;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/payment-intents/{id}', \kohortpay\sdk\Models\Operations\FindOnePaymentIntentRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\FindOnePaymentIntentResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
	
    /**
     * Cancel a Payment Intent by ID
     * 
     * @param \kohortpay\sdk\Models\Operations\CancelPaymentIntentSecurity $security
     * @param string $id
     * @return \kohortpay\sdk\Models\Operations\CancelPaymentIntentResponse
     */
	public function cancel(
        \kohortpay\sdk\Models\Operations\CancelPaymentIntentSecurity $security,
        string $id,
    ): \kohortpay\sdk\Models\Operations\CancelPaymentIntentResponse
    {
        $request = new \kohortpay\sdk\Models\Operations\CancelPaymentIntentRequest();
        $request->id = $id;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/payment-intents/{id}/cancel', \kohortpay\sdk\Models\Operations\CancelPaymentIntentRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \kohortpay\sdk\Models\Operations\CancelPaymentIntentResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200 or $httpResponse->getStatusCode() === 400) {
        }

        return $response;
    }
}